---
name: build
on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      simd: ${{ steps.set-matrix.outputs.simd }}
      os: ${{ steps.set-matrix.outputs.os }}
    steps:
    - id: set-matrix
      run: echo "::set-output name=os::{\"include\":{\"os\":\"ubuntu\"}}"
      run: echo "::set-output name=simd::{\"include\":[{\"simd\":\"avx\"},{\"simd\":\"sse2\"}]}"

  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.setup.outputs.simd)}}
    steps:
    - run: echo ${{matrix.simd}}
