---
name: build
on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      #run: echo "::set-output name=matrix::{\"include\":[{\"project\":\"foo\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"
      #run: echo "::set-output name=matrix::{\"include\":[{\"project\":[{\"simd\":\"one\"},{\"simd\":\"two\"}]}]}"
      #run: echo "::set-output name=matrix::{\"include\":{\"os\":\"ubuntu\",\"simd\":[\"sse2\",\"avx\"]}}"
      run: echo "::set-output name=matrix::{\"include\":[{\"os\":\"ubuntu\"}]}"
  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    - run: echo ${{matrix.simd}}
