---
name: build
on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: |
        echo "::set-output name=matrix::{\"include\":[{\"simd\":\"avx\", \"os\":\"ubuntu-latest\"},{\"simd\":\"sse2\",\"os\":\"ubuntu-latest\"}]}"

  build:
    needs: setup
    strategy:
      matrix: ${{fromJson(needs.setup.outputs.matrix)}}
    runs-on: ${{ matrix.os }}
    steps:
    - run: echo ${{matrix.simd}}
